service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
  iamRoleStatements:
    - ${file(./iam/IAMAuctionsTables.yaml):AuctionsTableIAM}
    

resources:
  Resources:
    AuctionsTable: ${file(./resources/AuctionsTable.yaml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET  
          path: /auctions
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http: 
          method: PATCH
          path: /auction/{id}/bid
  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(1 minute)

custom:
  AuctionsTable:
    name : !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundle:
    linting: false
  #   minify: true
  #   sourcemaps: true
  #   exclude:
  #     - aws-sdk
  #   webpackConfig: ./webpack.config.js
  # serverless-offline:
  #   httpPort: 3000
